[phases.setup]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install --upgrade setuptools wheel"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn kue_maza.wsgi:application"
